name: Deploy to EC2

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy.yml
      - terraform-helloworld.tf
      - public/*
      - src/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY_BASE64: ${{ secrets.PRIVATE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Terraform Init
        run: |
          cd terraform-helloworld
          terraform init -var="private_key_base64=${{ env.PRIVATE_KEY_BASE64 }}" -var="aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" -var="aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Apply
        run: |
          cd terraform-helloworld
          terraform apply -auto-approve -var="private_key_base64=${{ env.PRIVATE_KEY_BASE64 }}" -var="aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" -var="aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-18-117-70-110.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Copy build files to EC2
        run: |
          scp -i ~/.ssh/id_rsa -r build/* ec2-user@ec2-18-117-70-110.us-east-2.compute.amazonaws.com:/var/www/html

      - name: Run setup script on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@ec2-18-117-70-110.us-east-2.compute.amazonaws.com << 'EOF'
            sudo yum update -y
            sudo yum install -y httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd
            sudo chown ec2-user:ec2-user /var/www/html
            sudo systemctl restart httpd
          EOF

