name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-3-138-67-146.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}auto

      - name: Deploy to EC2
        run: |
          scp -i ~/.ssh/id_rsa hello.html ec2-user@ec2-3-138-67-146.us-east-2.compute.amazonaws.com:/var/www/html
          ssh -i ~/.ssh/id_rsa ec2-user@ec2-3-138-67-146.us-east-2.compute.amazonaws.com "chmod 644 /var/www/html/hello.html"
