name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve

      - name: Debug EC2 IP
        run: |
          terraform output -raw public_ip > ec2_ip.txt
          echo "EC2 IP Address:"
          cat ec2_ip.txt

      - name: Check if IP file exists
        run: |
          if [ ! -f ec2_ip.txt ]; then
            echo "File ec2_ip.txt not found!"
            exit 1
          fi

      - name: Wait for EC2 instance to be ready
        run: sleep 60  # Increased wait time to ensure the instance is ready

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          IP=$(cat ec2_ip.txt)
          if [ -z "$IP" ]; then
            echo "No IP address found!"
            exit 1
          fi
          ssh-keyscan -H $IP >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          IP=$(cat ec2_ip.txt)
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@$IP echo "SSH connection established"

      - name: Run setup script on EC2
        run: |
          IP=$(cat ec2_ip.txt)
          ssh -i ~/.ssh/id_rsa ec2-user@$IP << 'EOF'
            sudo yum update -y
            sudo yum install -y httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd
            sudo chown ec2-user:ec2-user /var/www/html
          EOF

      - name: Copy files to EC2
        run: |
          IP=$(cat ec2_ip.txt)
          scp -i ~/.ssh/id_rsa -r build/* ec2-user@$IP:/var/www/html

      - name: Restart Apache
        run: |
          IP=$(cat ec2_ip.txt)
          ssh -i ~/.ssh/id_rsa ec2-user@$IP 'sudo systemctl restart httpd'
