name: Edit EC2 Instance

on:
  push:
    branches:
      - master
    paths:
      - src/*  # Adjust paths as needed
      - .github/workflows/edit-instance.yml

jobs:
  edit-instance:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}

    steps:
      - name: Decode private key
        run: |
          echo ${{ env.PRIVATE_KEY_BASE64 }} | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Get EC2 Public IP
        id: get_ip
        run: |
          # Fetch the public IP from Terraform output or another source
          echo "::set-output name=public_ip::$(terraform output -raw public_ip)"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ steps.get_ip.outputs.public_ip }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 Instance and update folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.get_ip.outputs.public_ip }}
          username: ec2-user
          key: ${{ env.PRIVATE_KEY_BASE64 }}
          script: |
            cd /var/www/html
            git pull origin master
        env:
          DEBUG: true
