name: Edit EC2 Instance

on:
  push:
    branches:
      - master
    paths:
      - 'src/*'
      - '.github/workflows/edit-ec2.yml'

jobs:
  edit-instance:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY_BASE64: ${{ secrets.PRIVATE_KEY }}
      PRIVATE_KEY2: ${{ secrets.PRIVATE_KEY2 }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Decode private key
        run: |
            echo ${{ env.PRIVATE_KEY_BASE64 }} | base64 --decode > terraform-key-pairs.pem
            chmod 600 terraform-key-pairs.pem

      - name: SSH into EC2 Instance and update folder
        uses: appleboy/ssh-action@master
        with:
            host: ec2-18-117-70-110.us-east-2.compute.amazonaws.com
            username: ec2-user
            key: ${{ env.PRIVATE_KEY2 }}
            script: |
              # Navigate to project directory and perform updates
              cd /var/www/html
              # Example: pull changes if it's a git repo or otherwise update files
              # git pull origin master
              # Or copy new files if necessary
        env:
          DEBUG: true
